import { homedir, platform } from "node:os";
import { join, resolve } from "node:path";
import {
  moduleDir,
  parseToml,
  pathExists,
  readText,
  writeText,
} from "./runtime.ts";

export type InjectConfig = {
  cursor_rules_dir: string;
  cursor_mcp_file: string;
  claude_file: string;
  codex_file: string;
  codex_config: string;
  zed_settings_file: string;
  zed_agents_file: string;
};

export type BrainConfig = {
  vault_path: string;
  inject: InjectConfig;
};

/** Cross-OS defaults using ~ (expanded at resolve time). */
export function platformInjectDefaults(): InjectConfig {
  const isWin = platform() === "win32";
  // Zed: macOS/Linux ~/.config/zed; Windows %APPDATA%\Zed
  const zedRoot = isWin
    ? join(process.env.APPDATA || join(homedir(), "AppData", "Roaming"), "Zed")
    : join(homedir(), ".config", "zed");

  return {
    cursor_rules_dir: "~/.cursor/rules",
    cursor_mcp_file: "~/.cursor/mcp.json",
    claude_file: "~/.claude/CLAUDE.md",
    codex_file: "~/.codex/AGENTS.md",
    codex_config: "~/.codex/config.toml",
    zed_settings_file: join(zedRoot, "settings.json"),
    zed_agents_file: join(zedRoot, "AGENTS.md"),
  };
}

const DEFAULTS: BrainConfig = {
  vault_path: "~/Obsidian/My Brain",
  inject: platformInjectDefaults(),
};

export function expandHome(path: string): string {
  if (path === "~") return homedir();
  if (path.startsWith("~/")) return join(homedir(), path.slice(2));
  // Windows-style %USERPROFILE%
  if (path.includes("%USERPROFILE%")) {
    return path.replaceAll("%USERPROFILE%", homedir());
  }
  return path;
}

export function resolveVaultPath(configured: string, override?: string): string {
  const raw = process.env.BRAIN_VAULT?.trim() || override?.trim() || configured;
  return resolve(expandHome(raw));
}

function repoRoot(): string {
  return resolve(moduleDir(import.meta.url), "..");
}

export async function loadConfig(): Promise<BrainConfig> {
  const defaults: BrainConfig = {
    vault_path: DEFAULTS.vault_path,
    inject: platformInjectDefaults(),
  };
  const configPath = join(repoRoot(), "config.toml");

  if (!(await pathExists(configPath))) {
    return structuredClone(defaults);
  }

  const parsed = parseToml<
    Partial<BrainConfig> & { inject?: Partial<InjectConfig> }
  >(await readText(configPath));
  const inj = platformInjectDefaults();

  return {
    vault_path: parsed.vault_path ?? defaults.vault_path,
    inject: {
      cursor_rules_dir: parsed.inject?.cursor_rules_dir ?? inj.cursor_rules_dir,
      cursor_mcp_file: parsed.inject?.cursor_mcp_file ?? inj.cursor_mcp_file,
      claude_file: parsed.inject?.claude_file ?? inj.claude_file,
      codex_file: parsed.inject?.codex_file ?? inj.codex_file,
      codex_config: parsed.inject?.codex_config ?? inj.codex_config,
      zed_settings_file:
        parsed.inject?.zed_settings_file ?? inj.zed_settings_file,
      zed_agents_file: parsed.inject?.zed_agents_file ?? inj.zed_agents_file,
    },
  };
}

/** Write config.toml for a chosen vault path (portable ~ form when under home). */
export async function writeConfig(vaultPathInput: string): Promise<string> {
  const abs = resolveVaultPath(vaultPathInput);
  const home = homedir();
  const vaultForToml = abs.startsWith(home)
    ? `~/${abs.slice(home.length).replace(/^[/\\]/, "").split("\\").join("/")}`
    : abs.split("\\").join("/");

  const body = `# Generated by setup. BRAIN_VAULT env overrides vault_path.

vault_path = ${JSON.stringify(vaultForToml)}

[inject]
# Leave defaults unless you need custom harness paths.
# Zed paths are OS-specific and resolved at runtime if omitted from an older config.
`;

  const configPath = join(repoRoot(), "config.toml");
  await writeText(configPath, body);
  return configPath;
}

export function configDir(): string {
  return repoRoot();
}
